[package]
name = "vke"
version = "0.1.0"
authors = ["Victor Hermann Chiletto <victor.vasconceloschiletto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.30.0"
sdl2 = "0.33.0"
memoffset = "0.5.4"
glam = { version = "0.8.7" }
png = "0.16.4"
parking_lot = "0.10.2"
